name: Validate pull request
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            norelease
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
